# Generated by Django 5.2.6 on 2026-07-29 09:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='FiCompass', help_text='React feather icon name e.g. FiCompass, FiLayers, FiShield', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactEnquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'contact enquiry',
                'verbose_name_plural': 'contact enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='FiLayers', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to='partners/')),
                ('website', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='CompilVision', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_logos/')),
                ('tagline', models.CharField(default='Premium event management platform', max_length=255)),
                ('support_email', models.EmailField(default='support@compilvision.com', max_length=254)),
                ('support_phone', models.CharField(default='+1 (555) 000-0000', max_length=50)),
                ('address', models.TextField(default='123 Innovation Way, Tech District, CA 94016')),
                ('footer_content', models.TextField(default='Premium event management platform for professional hosting. Coordinate registrations, tickets, and analytics seamlessly.')),
                ('copyright', models.CharField(default='CompilVision. All rights reserved.', max_length=255)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('about_hero_title', models.CharField(default='About Our Platform', max_length=255)),
                ('about_hero_subtitle', models.TextField(default="We power the world's best professional events with class-leading tools.")),
                ('about_hero_banner', models.ImageField(blank=True, null=True, upload_to='about_banners/')),
                ('about_story_title', models.CharField(default='Our Story', max_length=255)),
                ('about_story_content', models.TextField(default='Founded in 2026, CompilVision started with a single mission: to make organizing and attending professional summits, workshops, and mixers as seamless and modern as possible.')),
                ('about_story_image', models.ImageField(blank=True, null=True, upload_to='about_story/')),
                ('mission', models.TextField(default='To empower organizers and connect professional communities through premium experiences.')),
                ('vision', models.TextField(default='To become the global standard platform for premium business and tech gatherings.')),
                ('contact_hero_title', models.CharField(default='Get in Touch', max_length=255)),
                ('contact_hero_subtitle', models.TextField(default='Have questions or need support? Drop us a line and our team will get back to you shortly.')),
                ('business_hours', models.TextField(default='Monday – Friday: 9:00 AM – 6:00 PM\nSaturday: 10:00 AM – 4:00 PM')),
                ('google_maps_embed_url', models.TextField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3153.0863773121575!2d-122.40137538468205!3d37.78528597975716!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80858062828bbf11%3A0xe539130761e3895e!2sSilicon%20Valley!5e0!3m2!1sen!2sus!4v1614123456789!5m2!1sen!2sus')),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=150)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
