# Generated by Django 6.0.6 on 2026-07-27 17:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='event_banners/', verbose_name='event banner')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic'), ('CULTURAL', 'Cultural'), ('SPORTS', 'Sports'), ('TECHNICAL', 'Technical'), ('WORKSHOP', 'Workshop'), ('SEMINAR', 'Seminar'), ('CONFERENCE', 'Conference'), ('NETWORKING', 'Networking'), ('SOCIAL', 'Social'), ('OTHER', 'Other')], default='OTHER', max_length=50, verbose_name='category')),
                ('description', models.TextField(verbose_name='description')),
                ('max_participants', models.PositiveIntegerField(verbose_name='max participants')),
                ('enable_waitlist', models.BooleanField(default=False, verbose_name='enable waitlist')),
                ('start_datetime', models.DateTimeField(verbose_name='start date & time')),
                ('end_datetime', models.DateTimeField(verbose_name='end date & time')),
                ('venue', models.CharField(max_length=255, verbose_name='venue / location')),
                ('registration_deadline', models.DateTimeField(verbose_name='registration deadline')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='contact email')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=20, verbose_name='status')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='rejection reason')),
                ('rejected_date', models.DateTimeField(blank=True, null=True, verbose_name='rejected date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='organizer')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ['-created_at'],
            },
        ),
    ]
