# Generated by Django 6.0.6 on 2026-07-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='contact phone'),
        ),
        migrations.AddField(
            model_name='event',
            name='social_links',
            field=models.JSONField(blank=True, default=dict, help_text='Dict of platform to URL, e.g. {"twitter": "https://..."}.', verbose_name='social links'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of tag strings.', verbose_name='tags'),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Set to 0 for free events.', max_digits=10, verbose_name='ticket price'),
        ),
        migrations.AddField(
            model_name='event',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=10, verbose_name='visibility'),
        ),
        migrations.AddField(
            model_name='event',
            name='website',
            field=models.URLField(blank=True, verbose_name='website'),
        ),
    ]
