# Generated by Django 6.0.6 on 2026-07-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_add_completed_status_and_status_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='True if this is a paid event.', verbose_name='is paid'),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Event fee. Must be > 0 for paid events. Automatically 0 for free events.', max_digits=10, verbose_name='price'),
        ),
    ]
