# Generated by Django 5.2.6 on 2026-07-29 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_status'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='events.event', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('REGISTRATION', 'Registration'), ('EVENT_UPDATE', 'Event Update'), ('EVENT_CANCELLED', 'Event Cancelled'), ('REMINDER', 'Reminder'), ('WAITLIST', 'Waitlist'), ('SYSTEM', 'System'), ('EVENT_SUBMITTED', 'Event Submitted'), ('EVENT_APPROVED', 'Event Approved'), ('EVENT_REJECTED', 'Event Rejected'), ('NEW_REGISTRATION', 'New Registration'), ('REGISTRATION_CANCELLED', 'Registration Cancelled'), ('GENERAL', 'General')], default='GENERAL', max_length=30, verbose_name='notification type'),
        ),
    ]
