# Generated by Django 5.2.6 on 2026-07-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('REGISTRATION', 'Registration'), ('EVENT_UPDATE', 'Event Update'), ('EVENT_CANCELLED', 'Event Cancelled'), ('REMINDER', 'Reminder'), ('WAITLIST', 'Waitlist'), ('SYSTEM', 'System'), ('EVENT_SUBMITTED', 'Event Submitted'), ('EVENT_APPROVED', 'Event Approved'), ('EVENT_REJECTED', 'Event Rejected'), ('NEW_REGISTRATION', 'New Registration'), ('REGISTRATION_CANCELLED', 'Registration Cancelled'), ('GENERAL', 'General'), ('PAYMENT_RECEIVED', 'Payment Received')], default='GENERAL', max_length=30, verbose_name='notification type'),
        ),
    ]
