# Generated by Django 6.0.6 on 2026-07-27 18:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_type', models.CharField(choices=[('GENERAL', 'General'), ('VIP', 'VIP'), ('STUDENT', 'Student')], default='GENERAL', max_length=20, verbose_name='ticket type')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='registration date')),
                ('attendance_status', models.CharField(choices=[('REGISTERED', 'Registered'), ('ATTENDED', 'Attended'), ('NO_SHOW', 'No Show')], default='REGISTERED', max_length=20, verbose_name='attendance status')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20, verbose_name='payment status')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event', verbose_name='event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL, verbose_name='participant')),
            ],
            options={
                'verbose_name': 'registration',
                'verbose_name_plural': 'registrations',
                'ordering': ['-registration_date'],
                'unique_together': {('event', 'participant')},
            },
        ),
    ]
