# Generated by Django 5.2.6 on 2026-07-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='Auto-generated QR code image for this registration ticket.', null=True, upload_to='registration_qr_codes/', verbose_name='QR code'),
        ),
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('WAITLISTED', 'Waitlisted'), ('CANCELLED', 'Cancelled')], db_index=True, default='CONFIRMED', max_length=20, verbose_name='registration status'),
        ),
    ]
