# Generated by Django 6.0.6 on 2026-07-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_registration_status_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='currency'),
        ),
        migrations.AddField(
            model_name='registration',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='amount paid'),
        ),
        migrations.AddField(
            model_name='registration',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='paid at'),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_intent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe payment intent ID'),
        ),
        migrations.AddField(
            model_name='registration',
            name='stripe_session_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Stripe session ID'),
        ),
    ]
