# Generated by Django 6.0.6 on 2026-07-27 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='organizer_covers/', verbose_name='cover image')),
                ('display_name', models.CharField(blank=True, max_length=150, verbose_name='display name')),
                ('title', models.CharField(blank=True, help_text='e.g. Event Director, Community Manager', max_length=100, verbose_name='organizer title')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='country')),
                ('biography', models.TextField(blank=True, verbose_name='biography')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter / X')),
                ('accomplishments', models.JSONField(blank=True, default=list, help_text='List of accomplishment strings.', verbose_name='accomplishments')),
                ('experience', models.JSONField(blank=True, default=list, help_text='List of experience / track record strings.', verbose_name='experience & track record')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'organizer profile',
                'verbose_name_plural': 'organizer profiles',
            },
        ),
        migrations.CreateModel(
            name='OrganizerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_daily_digest', models.BooleanField(default=True, verbose_name='receive daily digest')),
                ('desktop_notifications', models.BooleanField(default=True, verbose_name='desktop notifications')),
                ('public_profile', models.BooleanField(default=True, verbose_name='public organizer profile')),
                ('enable_2fa', models.BooleanField(default=False, verbose_name='enable two-factor authentication')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_settings', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'organizer settings',
                'verbose_name_plural': 'organizer settings',
            },
        ),
    ]
